### PR TITLE
Encrypting and decrypting the payload for sspi_negotiate auth

### PR DESCRIPTION
**Pull request by NimishaS**

### CODE REVIEW

**Comment by NimishaS** [comment]
@nahi , can you please review this? We have tested this with `knife bootstrap windows winrm` command and it works fine.
Travis is failing for `Ruby:jruby-head` but we couldn't reproduce this on our local machine. This issue exist for almost all other open PRs as well.

**Comment by mwrock** [comment]
would love to see this added

**Comment by nahi** [comment]
@NimishaS thanks for the PR. Could you provide spec or document of this feature? I want to understand the spec before changing httpclient's filter protocol.

With regards to jruby-head failure I filed this issue: https://github.com/jruby/jruby/issues/3577

**Comment by NimishaS** [comment]
@nahi , Updated the Readme.
Tried to write specs too but couldn't use `WEBrick::HTTPAuth` for the same. It also doesn't seem possible to assert if `encrypt_payload` and `decrypt_payload` methods are being called inside `filter_request` method for `sspi_negotiate` auth.

**Comment by NimishaS** [comment]
@nahi , any updates on this?

**Comment by NimishaS** [comment]
https://github.com/chef/knife-windows/pull/334 drops the requirement of this patch. So closing this one.

**Pull request closed without merging**
