### PR TITLE
Abrandoned/fix 322 324

### PR DESCRIPTION
**Pull request by abrandoned**
Don't know what is going on but these tests would fail on ubuntu 12.04 and 14.04 with java 8 but on my mac I can't trigger a failure .... probably need to dig deeper but this is something that does resolve 322 and 324

### CODE REVIEW

**Comment by abrandoned** [comment]
@quixoten can you post about linux version and java version and verify that the test breaks before the patch is applied? (I see the output in the issue and have seen this fail on ubuntu but working from mac now and can't trigger a failure)

**Comment by abrandoned** [comment]
also don't like that a test is reaching out to google, but couldn't think of another way to test the failure scenario when public CA's were not being respected when a ca cert is added

**Comment by abrandoned** [comment]
should not be needed as java would throw an exception if same aliases are in use and #327 fixes the main issue

**Comment by nahi** [comment]
Thanks for the confirmation, and sorry for the trouble 2.8.1 introduced...

**Pull request closed without merging**
