### PR TITLE
fix for #256 and #257

### PR DESCRIPTION
**Pull request by binaryplease**
fix for #256 and #257

The timeout option for getting the head is broken. This is a fix/workaround for it.

### CODE REVIEW

**Comment by binaryplease** [comment]
I dont understand the problem with my fix?

**Comment by carsonreinke** [comment]
This is what `timeout` does already, is it not?  Besides that, it is possible that you are leaving that Thread unchecked after the `join`, and it will just continue to run.

**Comment by binaryplease** [comment]
> This is what timeout does already, is it not? 

I don't, think so. I have not checked what timeout does exactly in the background but it is known to be broken for multithreaded applications. I ran into problems with the original timeout around the method, getting the head never timed out etc. (see ticket), I havent had the problem since this fix. It can be a bing coincidence, but I dont't think so.

> Besides that, it is possible that you are leaving that Thread unchecked after the join, and it will just continue to run.

If nil is returned (join timed out) the program will continue anyway. That is true, but changing

```` ruby
raise ReceiveTimeoutError if success.nil?
````

to 

````ruby
if success.nil?
raise ReceiveTimeoutError 
t.kill unless t.nil?
```` 

should fix that.

Excuse me if I'm wrong, just trying to help. If you have a better way to solve/workaround for #257 please let me know.

**Comment by carsonreinke** [comment]
Thats what `timeout` does, see it here: https://github.com/ruby/ruby/blob/v2_2_2/lib/timeout.rb

Timeout is not broken, the concept of stopping a thread is not safe to any shared variables since the state of those could be inconsistent.

Sounds like a JRuby or OS problem.  Any reproducible tests?

**Comment by nahi** [comment]
Sure, httpclient expect Ruby implementation provides interruptible Socket implementation. Perhaps that version of JRuby has a bug. And as @carsonreinke explained, JRuby has similar implementation internally. Could you try to update JRuby version? Thanks!

**Pull request closed without merging**
